name: "build"
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    # Here we install all the tools : docker buildx, QEMU, JDK 11, JFrog CLI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install prerequisites
      - name: Install Node
        uses: actions/setup-node@v3
        with:
            node-version: 18
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          # JFrog platform url (for example: https://acme.jfrog.io)
          JF_URL: ${{ vars.JF_URL }}
          # JFrog Platform access token
          JF_ACCESS_TOKEN: ${{ vars.JF_ACCESS_TOKEN }}
      # - name: NPM Audit 
      #   env:
      #     JFROG_CLI_BUILD_NAME: 'roybs-nodejs-project'
      #     JF_ENV_1: ${{ vars.JF_SECRET_ENV_1 }}
      #     JFROG_CLI_BUILD_PROJECT: roybs
      #   run: |
      #     jf rt bce ${{ env.JFROG_CLI_BUILD_NAME }} $GITHUB_RUN_NUMBER 
      #     jf rt bag ${{ env.JFROG_CLI_BUILD_NAME }} $GITHUB_RUN_NUMBER
      #     jf npmc --repo-resolve roybs-npm-unsecure-remote
      #     jf npm i --omit dev --build-name=${{ env.JFROG_CLI_BUILD_NAME }} --build-number=$GITHUB_RUN_NUMBER
      #     jf audit --npm --fail=false
      - name: Docker build 
        env:
          JFROG_CLI_BUILD_NAME: 'roybs-nodejs-demo'
          JF_HOST: ${{ vars.JF_URL }}
          JFROG_CLI_BUILD_PROJECT: roybs
        run: |
          docker build . -t ${{ env.IMAGE_NAME }}:$GITHUB_RUN_NUMBER
          docker images
          jf config show 
          jf rt ping 
          docker tag ${{ env.IMAGE_NAME }}:${{ github.run_number }} ${{ vars.DOCKER_REG_SRV }}/${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
          docker images
          jf docker push ${{ vars.DOCKER_REG_SRV }}/${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ github.run_number }} --build-name=${{ env.BUILD_NAME }} --build-number=${{ github.run_number }}
          jf rt bp $JFROG_CLI_BUILD_NAME $GITHUB_RUN_NUMBER



          