name: "build"
on: 
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    # Here we install all the tools : docker buildx, QEMU, JDK 11, JFrog CLI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install prerequisites
      - name: Install Node
        uses: actions/setup-node@v3
        with:
            node-version: 18
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          # JFrog platform url (for example: https://acme.jfrog.io)
          JF_URL: ${{ vars.JF_URL }}
          JF_PROJECT: guy
        with:
          oidc-provider-name: "guy-github"

      - name: NPM Config
        run: jf npmc --server-id-resolve=setup-jfrog-cli-server --server-id-deploy=setup-jfrog-cli-server --repo-deploy ${{ vars.NPM_REPO }} --repo-resolve ${{ vars.NPM_REPO }} --global
        
      - name: Curation audit 
        run: |
          jf curation-audit
          
      - name: Docker build and push 
        env:
          JF_HOST: ${{ vars.JF_URL }}
          # JFROG_CLI_BUILD_PROJECT: guy
        run: |
          jf docker login "${{ env.JF_DOCKER_REGISTRY }}" -u "${{ steps.jf.outputs.oidc-user }}" -p "${{ steps.jf.outputs.oidc-token }}"
          jf docker build . -t ${{ vars.IMAGE_NAME }}:$GITHUB_RUN_NUMBER
          docker tag ${{ vars.IMAGE_NAME }}:${{ github.run_number }} ${{ vars.DOCKER_REG_SRV }}/${{ vars.DOCKER_REPO }}/${{ vars.IMAGE_NAME }}:${{ github.run_number }}
          jf docker push ${{ vars.DOCKER_REG_SRV }}/${{ vars.DOCKER_REPO }}/${{ vars.IMAGE_NAME }}:${{ github.run_number }} --build-name=${{ vars.BUILD_NAME }} --build-number=${{ github.run_number }}

      - name: Collect and Publish Build Info
        run: |
          # Collect environment variables for the build
          jf rt bce
          # Collect VCS details from git and add them to the build
          jf rt bag
          # Publish build info
          jf rt bp ${{ vars.BUILD_NAME }} $GITHUB_RUN_NUMBER 

      - name: Security Audit
        run: | 
          jf audit
        
      - name: Scan Build
        run: | 
          jf bs ${{ vars.BUILD_NAME }} $GITHUB_RUN_NUMBER --fail=false --vuln --format table --rescan 

          
