name: "build"
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    # Here we install all the tools : docker buildx, QEMU, JDK 11, JFrog CLI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install prerequisites
      - name: Install Node
        uses: actions/setup-node@v3
        with:
            node-version: 18
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          # JFrog platform url (for example: https://acme.jfrog.io)
          JF_URL: ${{ secrets.JF_URL }}
          # JFrog Platform access token
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      # - name: NPM Audit 
      #   env:
      #     JFROG_CLI_BUILD_NAME: 'roybs-nodejs-project'
      #     JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
      #     JFROG_CLI_BUILD_PROJECT: roybs
      #   run: |
      #     jf rt bce ${{ env.JFROG_CLI_BUILD_NAME }} $GITHUB_RUN_NUMBER 
      #     jf rt bag ${{ env.JFROG_CLI_BUILD_NAME }} $GITHUB_RUN_NUMBER
      #     jf npmc --repo-resolve roybs-npm-unsecure-remote
      #     jf npm i --omit dev --build-name=${{ env.JFROG_CLI_BUILD_NAME }} --build-number=$GITHUB_RUN_NUMBER
      #     jf audit --npm --fail=false
      - name: Docker build 
        env:
          JFROG_CLI_BUILD_NAME: 'roybs-nodejs-project'
          JF_HOST: ${{ secrets.JF_URL }}
          JFROG_CLI_BUILD_PROJECT: roybs
        run: |
          docker build . -t roybs-nodejs-project:$GITHUB_RUN_NUMBER
          docker images
          jf config show 
          docker tag roybs-nodejs-project:$GITHUB_RUN_NUMBER $JF_HOST/roybs-docker-dev-local/roybs-nodejs-project:$GITHUB_RUN_NUMBER
          docker images
          jf docker push $JF_HOST/roybs-docker-dev-local/roybs-nodejs-project:$GITHUB_RUN_NUMBER --build-name=$JFROG_CLI_BUILD_NAME --build-number=$GITHUB_RUN_NUMBER 
          jf rt bp $JFROG_CLI_BUILD_NAME $GITHUB_RUN_NUMBER